---

services:
  jenkins:
    image: $JENKINS_IMAGE
    container_name: $JENKINS_NAME
    restart: unless-stopped
    ports:
      - "$JENKINS_PORT:8080"
      - "$AGENT_PORT:50000"
    volumes:
      - $JENKINS_HOME:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=$MASTER_WIZARD
    networks:
      network:
        ipv4_address: ${JENKINS_HOST}

networks:
  network:
    name: ${JENKINS_NET}
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: ${JENKINS_ADDR}
          gateway: ${JENKINS_GATE}

